// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDGos0h66YgKBYqeiBKQ1acOn8Y32Efi4',
    appId: '1:745853868107:web:f265919bbf92c79c4515ce',
    messagingSenderId: '745853868107',
    projectId: 'mobile-app-c5b1d',
    authDomain: 'mobile-app-c5b1d.firebaseapp.com',
    databaseURL: 'https://mobile-app-c5b1d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-app-c5b1d.firebasestorage.app',
    measurementId: 'G-KRQXHCSGPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK31cDkz9CXtCY-p59duD2QQGkMQb0mRY',
    appId: '1:745853868107:android:77685a84f1df1b3c4515ce',
    messagingSenderId: '745853868107',
    projectId: 'mobile-app-c5b1d',
    databaseURL: 'https://mobile-app-c5b1d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-app-c5b1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPFF910U1I1FRGW2sauUrY32JXcJmFAc0',
    appId: '1:745853868107:ios:47617c1b607e65234515ce',
    messagingSenderId: '745853868107',
    projectId: 'mobile-app-c5b1d',
    databaseURL: 'https://mobile-app-c5b1d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-app-c5b1d.firebasestorage.app',
    iosBundleId: 'com.example.skyfrog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPFF910U1I1FRGW2sauUrY32JXcJmFAc0',
    appId: '1:745853868107:ios:47617c1b607e65234515ce',
    messagingSenderId: '745853868107',
    projectId: 'mobile-app-c5b1d',
    databaseURL: 'https://mobile-app-c5b1d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-app-c5b1d.firebasestorage.app',
    iosBundleId: 'com.example.skyfrog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDGos0h66YgKBYqeiBKQ1acOn8Y32Efi4',
    appId: '1:745853868107:web:0d450f1eeb8be9ff4515ce',
    messagingSenderId: '745853868107',
    projectId: 'mobile-app-c5b1d',
    authDomain: 'mobile-app-c5b1d.firebaseapp.com',
    databaseURL: 'https://mobile-app-c5b1d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-app-c5b1d.firebasestorage.app',
    measurementId: 'G-XET7WMK1XN',
  );
}
