// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAruYDyIXBon3XqwQke9L6_1CI_W6XFEwc',
    appId: '1:725529644795:web:8bccd4c2c9b1178fa7ea5e',
    messagingSenderId: '725529644795',
    projectId: 'skyfrog-app-741d3',
    authDomain: 'skyfrog-app-741d3.firebaseapp.com',
    storageBucket: 'skyfrog-app-741d3.firebasestorage.app',
    measurementId: 'G-V5GVQ3K3JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdf5RXfGO0YYmeRXYv6bPukJpc9l1cdu0',
    appId: '1:725529644795:android:cd2fa5ad90222d53a7ea5e',
    messagingSenderId: '725529644795',
    projectId: 'skyfrog-app-741d3',
    storageBucket: 'skyfrog-app-741d3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUNuDAEWBMQ7zFROcAHR9aILEZ3REs-1Q',
    appId: '1:725529644795:ios:cd758f3512efb7aca7ea5e',
    messagingSenderId: '725529644795',
    projectId: 'skyfrog-app-741d3',
    storageBucket: 'skyfrog-app-741d3.firebasestorage.app',
    iosBundleId: 'com.example.skyfrog',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUNuDAEWBMQ7zFROcAHR9aILEZ3REs-1Q',
    appId: '1:725529644795:ios:cd758f3512efb7aca7ea5e',
    messagingSenderId: '725529644795',
    projectId: 'skyfrog-app-741d3',
    storageBucket: 'skyfrog-app-741d3.firebasestorage.app',
    iosBundleId: 'com.example.skyfrog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAruYDyIXBon3XqwQke9L6_1CI_W6XFEwc',
    appId: '1:725529644795:web:d077c3ca927c5e30a7ea5e',
    messagingSenderId: '725529644795',
    projectId: 'skyfrog-app-741d3',
    authDomain: 'skyfrog-app-741d3.firebaseapp.com',
    storageBucket: 'skyfrog-app-741d3.firebasestorage.app',
    measurementId: 'G-XCRZ86YVEQ',
  );
}
